# Generated by Django 3.1.2 on 2020-11-02 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('age', models.IntegerField()),
                ('number', models.BigIntegerField(default='8888888888')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=10)),
                ('father', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('photo', models.ImageField(upload_to='pics')),
                ('dob', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=100, null=True)),
                ('mobile', models.BigIntegerField(blank=True, null=True)),
                ('college', models.CharField(blank=True, choices=[('college 1', 'college 1'), ('college 2', 'college 2'), ('college 3', 'college 3'), ('college 4', 'college 4'), ('college 5', 'college 5')], max_length=20, null=True)),
                ('degree', models.CharField(blank=True, choices=[('course 1', 'course 1'), ('course 2', 'course 2'), ('course 3', 'course 3'), ('course 4', 'course 4'), ('course 5', 'course 5')], max_length=25, null=True)),
                ('rdate', models.DateField(blank=True, null=True)),
                ('reg_no', models.IntegerField(default='1234')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='paystatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(blank=True, max_length=100, null=True)),
                ('s_reg_no', models.BigIntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(blank=True, max_length=100, null=True)),
                ('re_no', models.IntegerField(blank=True, null=True)),
                ('mobile', models.BigIntegerField(blank=True, null=True)),
                ('amount', models.BigIntegerField(default='25000')),
                ('pmode', models.CharField(choices=[('debit card', 'debit card'), ('net banking', 'net banking'), ('paypal', 'paypal')], default='', max_length=120)),
                ('pdate', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
