# Generated by Django 3.1.2 on 2020-11-03 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='re_no',
        ),
        migrations.RemoveField(
            model_name='register',
            name='reg_no',
        ),
    ]
