# Generated by Django 3.1.2 on 2020-11-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20201103_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='p_reg_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='reg_no',
            field=models.IntegerField(default='1234'),
        ),
    ]
