# Generated by Django 3.1.2 on 2020-11-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20201103_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='l_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='d_lname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='f_lname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='l_father',
            field=models.CharField(default='', max_length=100),
        ),
    ]
