# Generated by Django 3.1.2 on 2020-11-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_auto_20201104_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystatus',
            name='s_lname',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='l_name',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='p_name',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paystatus',
            name='s_name',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='d_lname',
            field=models.CharField(default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='d_name',
            field=models.CharField(default='N/A', max_length=100, null=True),
        ),
    ]
