# Generated by Django 3.1.2 on 2020-11-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_auto_20201105_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='college',
            field=models.CharField(blank=True, choices=[('Daulat Ram College', 'Daulat Ram College'), ('Gargi College', 'Gargi College'), ('Hindu College', 'Hindu College'), ('Hans Raj College', 'Hans Raj College'), ('Maharaja Agarsen College', 'Maharaja Agarsen College'), ('Delhi College of Arts & Commerce', 'Delhi College of Arts & Commerce')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='degree',
            field=models.CharField(blank=True, choices=[('B.Sc (Hons) Applied Life Science', 'B.Sc (Hons) Applied Life Science'), ('B.Sc (Hons) Electronics', 'B.Sc (Hons) Electronics'), ('B.Com (Hons) Corporate Laws', 'B.Com (Hons) Corporate Laws'), ('B.Sc (Hons) Mathematics', 'B.Sc (Hons) Mathematics'), ('B.A. (Hons) Economics', 'B.A. (Hons) Economics'), ('B.A (Hons) Psychology', 'B.A (Hons) Psychology')], max_length=200, null=True),
        ),
    ]
